### ISSUE TITLE
Fails To Open CLI

### ISSUE THREAD

**Issue by supersimple33** [nix2io/cli#75]
It seems like the plugins folder is not being created upon installation. Nix-CLI then searches for it and fails when it is not found.

```
$ nix-cli
checking for updates
internal/fs/utils.js:307
    throw err;
    ^

Error: ENOENT: no such file or directory, scandir '/Users/name/.nix-cli/plugins/'
    at Object.readdirSync (fs.js:1021:3)
    at ServiceCore.refreshPlugins (/usr/local/lib/node_modules/@nix2/nix-cli/node_modules/@nix2/service-core/dist/classes/ServiceCore.js:18:14)
    at new ServiceCore (/usr/local/lib/node_modules/@nix2/nix-cli/node_modules/@nix2/service-core/dist/classes/ServiceCore.js:13:14)
    at Object.<anonymous> (/usr/local/lib/node_modules/@nix2/nix-cli/dist/service.js:8:23)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18) {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '/Users/name/.nix-cli/plugins/'
}
```

The folder should either be created upon install or a catch should be added.

**Comment by k2on** [comment]
Good catch!
